baseURL = 'https://asleepingreed.com/'
languageCode = "zh"
defaultContentLanguage = "zh"
title = 'A Sleeping Reed'
theme = 'pensant'

[params]
  site_logo = "images/logo.svg"
  logo_height = "2.2rem" # 控制导航中 logo 显示高度，可改为例如 48px / 3rem
  description = "L'homme est un roseau pensant"
  mainSections = ["reading", "develop", "photography"]
  pensant_socials = [
    {name = "Github", url = "https://github.com/bingdian"},
  ]
  background_color_class = "bg-white"
  body_classes = "bg-white"
  cdn = "https://asleepingreed.com"

  [params.post]
    thumbnail = true
    thumbnail_height = "h-auto"
    thumbnail_width = "w-80 mw8"
    description = "200"

[Menus]
  main = [
      {Name = "首页", URL = "/", Weight = 1},
      {Name = "摄影", URL = "/photography/", Weight = 2},
      {Name = "阅读", URL = "/reading/", Weight = 4},
      {Name = "关于", URL = "/about/", Weight = 5}
  ]

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

[markup.goldmark.renderer]
	unsafe= true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true

[outputFormats]
  [outputFormats.MANIFEST]
    name = "manifest"
    baseName = "manifest"
    mediaType = "application/json"
    rel = "manifest"

[outputs]
    home = ["HTML", "RSS", "SITEMAP"]
    section = ["HTML", "RSS"]
    page = ["HTML"]
